-- IMPORT AND EXPORT

-- FIRST, WE CREATE A TABLE EXACTLY WITH THE SAME NUMBER OF COLUMNS (3) AS OUR .csv FILE
CREATE TABLE simple(
	a INTEGER,
	b INTEGER,
	c INTEGER
);

-- CLICK WITH THE RIGHT BUTON ON 'simple' TABLE CREATED, SELECT 'IMPORT/EXPORT DATA'
-- SET THE PATH FROM YOUR FILE
